name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist # Upload the built project directory

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: build # This ensures the deploy job only runs after the build job is successful
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.VITE_API_TOKEN }}
          accountId: ${{ secrets.VITE_ACCOUNT_ID }}
          projectName: deploy-react-app
          directory: dist # The downloaded artifact will be in the `dist` folder
