name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Define environment variables globally for the job
      VITE_API_ENDPOINTS: https://jsonplaceholder.typicode.com
      VITE_TEST_KEY=test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{secrets.VITE_API_TOKEN}}
          accountId: ${{secrets.VITE_ACCOUNT_ID}}
          projectName: deploy-react-app
          directory: dist
